POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "faraz@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "faraz@gmail.com",
  "password": "12345678"
}

###

GET http://localhost:3000/auth/whoami
Content-Type: application/json

###

GET http://localhost:3000/auth/signout
Content-Type: application/json
