### Register a user.

POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john@gmail.com",
  "password": "password"
}

### Login a user

POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "password"
}

### Get logged in user.

GET http://localhost:5000/api/v1/auth/whoami
Content-Type: application/json

### Signput a user.

GET http://localhost:5000/api/v1/auth/signout
Content-Type: application/json
